[package]
name = "vp_client"
version = "0.1.0"
authors = ["Dmitry Egorov <degorov86@gmail.com>"]

[dependencies]
bincode = "0.4"
rustc-serialize = "0.3.*"
byteorder = "0.3.*"

[dependencies.vp_shared]
path = "../vp_shared"
